### ISSUE TITLE
Commit on June 5th Broke Local PDF Builds

### ISSUE THREAD

**Issue by johnpflyer74** [tomjohnson1492/documentation-theme-jekyll#102]
We're finally updating the `expdocs` project from your original theme (_born many moons ago_) to your latest theme.

I downloaded your latest commit to test it before I rolled it out the the rest of the team and ran into an issue where PDFs weren't being generated.

Here are my steps to reproduce:

Working/serving/building/generating locally on my MacBook Pro.

1. Downloaded the latest theme.
1. Made sure all of my prerequisites were up-to-date.
1. Ran `jekyll serve` to make sure that everything was running locally.
1. Ran the PDF shell script `. pdf-mydoc.sh` to make sure I could generate PDFs. **No PDF was generated**.
1. I noticed an error in my terminal: `prince: error: no input documents to process`
1. I checked the `_site/pdfconfigs/princelist.txt` file. It was there, but it was empty ... well ... it had 4 empty lines.
1. I navigated to `http://127.0.0.1:4010/mydoc-pdf/tocpage/` and saw the **Table of Contents** `h1`, but the rest of the `HTML` page was blank.

This sent me on a two day odyssey where I tried everything I could think of to fix the issue, and I couldn't get anything to work. Before bothering any of the Developers, I decided to look at the commit history on the theme and I noticed a fair amount of work on the sidebar code [committed on June 5th](https://github.com/tomjohnson1492/documentation-theme-jekyll/commit/361d9f960e31baf80e1e83a7ddfad1510d4e8853). I downloaded the [June 3rd commit](https://github.com/tomjohnson1492/documentation-theme-jekyll/commit/c6038b7edeb91c625f465275233d6c6f18e906e2) and was able to generate the PDFs without issue.

I took a look at your changes on June 5th and they are _way_ over my head.

I will wait for a fix for the broken PDF generation process. In the mean time, I'm going to continue my work with the coded committed on June 3rd.

If the newest version of the theme isn't meant to be built locally, but instead is only meant to be built in a Docker Container or someplace else, please let me know and we can close this issue as **Won't FIx** (_or somethign like that_).

**Comment by moxiegirl** [comment]
I'm also seeing this problem as well on a fresh fork of your repo.  I'll try and debug the issue but some help appreciated too. 

@tomjohnson1492 can you test to confirm this issue also?

**Comment by tomjoht** [comment]
Thanks for the report about the bug. I fixed the issue. See [this commit](https://github.com/tomjohnson1492/documentation-theme-jekyll/commit/0397cb416276a324156cdd83ac716905763df411) for the changes.

**Comment by mary-thoughtspot** [comment]
Thanks. That sorted it.
