### ISSUE TITLE
Code block inside alert

### ISSUE THREAD

**Issue by OskarPersson** [tomjohnson1492/documentation-theme-jekyll#103]
What is the recommended way to insert code blocks inside an alert? The one below isn't rendering it as a code block.

```
{% include note.html content="This is my note. <br/><br/>

~~~
def foo(x):
    return x+1
~~~

" %}
```

**Comment by johnpflyer74** [comment]
As a general rule, whenever MarkDown fails, you have fallback to HTML:

```
{% include note.html content="This is my note. <br/><br/>
<code>
def foo(x):<br>
&nbsp;&nbsp;&nbsp;&nbsp;return x+1
</code>
" %}
```

In previous versions of documentation-theme-jekyll, the `<pre>` tag was supported. It doesn't seem to be working in 6.0, so you have to use `<br>` and `&nbsp;` to get the line breaks and spacing you're looking for.

**Comment by tomjoht** [comment]
Thanks for adding this note. I'll mention this in the documentation.

**Comment by tomjoht** [comment]
I added the note [here](http://idratherbewriting.com/documentation-theme-jekyll/mydoc_alerts.html#blockleveltags).
