### ISSUE TITLE
wkhtmltopdf as alternative to prince

### ISSUE THREAD

**Issue by chickahoona** [tomjohnson1492/documentation-theme-jekyll#104]
Currently the theme only supports the generation of pdfs based on prince which is quite expensive.

A free alternative to prince is [wkhtmltopdf ](https://wkhtmltopdf.org/) and support for it would be really awesome.

**Comment by tomjoht** [comment]
I experimented with this other tool, but I like Prince too much. If you're fine with the watermark on the homepage, then Prince is fine. Prince gives you way more advanced customization options and is more extensible. My purpose here is not to make an entirely open source tool, as even many open source themes rely on commercial services (e.g., Algolia with search) to make them work well.

**Comment by chickahoona** [comment]
Sad but ok :)
