### ISSUE TITLE
Liquid Warning: Liquid syntax error: Expected dotdot but found pipe

### ISSUE THREAD

**Issue by johnpflyer74** [tomjohnson1492/documentation-theme-jekyll#106]
I'm not planning on publishing on Github Pages, so I went with [Option 1: Build the Theme (without the github-pages gem)](http://idratherbewriting.com/documentation-theme-jekyll/index.html#option1). After deleting the `Gemfile` and `Gemfile.lock` files from the theme's root directory, I ran `jekyll serve` and received these Liquid Warnings:

```
 Generating...
    Liquid Warning: Liquid syntax error (line 93): Expected dotdot but found pipe in "{{(site.pages | sort: 'title') }}" in pages/mydoc/mydoc_kb_layout.md
    Liquid Warning: Liquid syntax error (line 140): Expected dotdot but found pipe in "{{(site.pages | sort: 'title') }}" in pages/mydoc/mydoc_tags.md
                    done in 7.298 seconds.
```

The site generated without issue, but I wasn't comfortable with the warnings, so I did a little research and found that [parentheses are not allowed within Liquid tags](https://github.com/Shopify/liquid/issues/362). I the offending lines had dot references to other liquid tags, so I searched around the project and removed the offending parentheses. After saving -> killing the old serve -> serving again in a new terminal, the warnings were gone.

**Comment by tomjoht** [comment]
Thanks. I believe these issues have been fixed, as I don't see {{( in the theme anymore. Thanks for the note.
