### ISSUE TITLE
Is there a way to generate sidebar yml files (semi)automatically?

### ISSUE THREAD

**Issue by i-give-up** [tomjohnson1492/documentation-theme-jekyll#110]
I'm referring to yml files such as `_data/sidebars/mydoc_sidebar.yml`.

It seems daunting to add entries to the yml files manually if you have a lot of content files.

I see a lot of sites using this approach (yml file) to build their sidebar navigation, so I was wondering if there's some standard/common workflow to creating that yml file automatically or semi-automatically based on say folder structures.

**Comment by tomjoht** [comment]
I see this received 10 likes. Well, there is a way to auto-populate the sidebar based on frontmatter properties. I created a tutorial for building out that navigation approach here: https://jekyllrb.com/tutorials/navigation/#scenario-8-retrieving-items-based-on-front-matter-properties

However, reworking this frontmatter-driven approach into the theme isn't something I currently have the bandwidth for. Also, it seems a bit tedious to rearrange the items in the sidebar if you have to go into all the individual files and change their frontmatter properties. For example, if the frontmatter has ordering 1, 2, 3, etc., and then you want to add a file, wouldn't you need to adjust the order of all the other files? Might not be a big deal, but I haven't coded my sidebar that way.
