### ISSUE TITLE
"Edit me" link in Special layouts->Shuffle layout is broken

### ISSUE THREAD

**Issue by geneotech** [tomjohnson1492/documentation-theme-jekyll#112]
It resolves to:

```
https://github.com/tomjoht/documentation-theme-jekyll/blob/gh-pages/pages/mydoc/mydoc_shuffle.md
```

It is because ``_layouts/page.html`` always assumes that the file is in ``.md`` format, while the ``mydoc_shuffle.html`` is an exception:

Line 44:
```
{{page.url | remove: ".html" | append: ".md"}}
```

**Comment by tomjoht** [comment]
This has been fixed. Thanks for reporting the issue.
