### ISSUE TITLE
Any hints to enable navigation with arrow keys in search result box?

### ISSUE THREAD

**Issue by ghost** [tomjohnson1492/documentation-theme-jekyll#116]
Tried various stackoverflow js snippets but failed so far. Maybe there's a ready to use solution?

**Comment by tomjoht** [comment]
wouldn't this just be a style you add? something like:

```
ul#results-container a::before {
    content: "--> ";
}
```

**Comment by ghost** [comment]
Not sure I understand what should content value be...

**Comment by tomjoht** [comment]
I'm closing this issue because I'm not sure the search box needs navigation hints. I don't fully understand the request as well (why would the search provide hints on navigation?).

**Comment by ghost** [comment]
I suspect that what's being requested here is hints about what to change in the template to enable using the arrow keys to move down into the dropdown list of search hits to choose one.

To illustrate what I mean: go to https://idratherbewriting.com/documentation-theme-jekyll/ and type "theme" into the search box. A dropdown list appears below the search box with a number of topic titles. I can't figure out a way with Chrome to move focus to that list in order to pick an item from it using just the keyboard.

All that said, I don't have the JS chops to suggest a solution.
