### ISSUE TITLE
Question: js and css not found

### ISSUE THREAD

**Issue by arturbosch** [tomjohnson1492/documentation-theme-jekyll#118]
Heyho,
I want to try out this theme but the site is not rendered as expected/does not look like the demo page.

I cloned the repo, installed bundler and jekyll, used bundle update, jekyll build and jekyll serve.
Now when navigating to `localhost:4000`, I get errors that some files are missing. Any ideas what to do? Thanks in advance!

```
Configuration file: /home/artur/Repos/documentation-theme-jekyll/_config.yml
            Source: /home/artur/Repos/documentation-theme-jekyll
       Destination: /home/artur/Repos/documentation-theme-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 2.799 seconds.
 Auto-regeneration: enabled for '/home/artur/Repos/documentation-theme-jekyll'
    Server address: http://127.0.0.1:4000/documentation-theme-jekyll/
  Server running... press ctrl-c to stop.
[2018-01-26 16:14:01] ERROR `/' not found.
[2018-01-26 16:14:01] ERROR `/css/modern-business.css' not found.
[2018-01-26 16:14:01] ERROR `/css/syntax.css' not found.
[2018-01-26 16:14:01] ERROR `/css/customstyles.css' not found.
[2018-01-26 16:14:01] ERROR `/css/theme-blue.css' not found.
[2018-01-26 16:14:01] ERROR `/js/jquery.navgoco.min.js' not found.
[2018-01-26 16:14:01] ERROR `/css/boxshadowproperties.css' not found.
[2018-01-26 16:14:01] ERROR `/js/customscripts.js' not found.
[2018-01-26 16:14:01] ERROR `/js/toc.js' not found.
[2018-01-26 16:14:01] ERROR `/js/jekyll-search.js' not found.
[2018-01-26 16:14:01] ERROR `/images/company_logo.png' not found.
[2018-01-26 16:14:02] ERROR `/js/jquery.navgoco.min.js' not found.
[2018-01-26 16:14:02] ERROR `/js/toc.js' not found.
[2018-01-26 16:14:02] ERROR `/js/customscripts.js' not found.
[2018-01-26 16:14:02] ERROR `/js/jekyll-search.js' not found.
[2018-01-26 16:14:02] ERROR `/images/company_logo.png' not found.
```

**Comment by tomjoht** [comment]
Not sure. Can you try deleting the existing Gemfile.lock file and running bundle install again? Also, can you confirm that you can build a vanilla jekyll site without issues? Also, what version of Jekyll are you running?

**Comment by arturbosch** [comment]
Still no luck.
Yes, I can confirm that my blogs are getting built with newest jekyll (3.7.2)

**Comment by chanakavp** [comment]
Instead of downloading, clone the repository. That worked for me. Wish
there was a clean-slate version of the beautiful demo site.

**Comment by arturbosch** [comment]
I cloned the repo, run `bundle install` and `bundle exec jekyll s`.
Also tried `bundle update`.
This is how the page looks like for me:
![2018-02-02-122416_1751x934_scrot](https://user-images.githubusercontent.com/20924106/35730880-04da4f3a-0814-11e8-814b-9b00f9147a44.png)

**Comment by kastork** [comment]
I noticed this in your error output

```
GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
done in 2.799 seconds.
```

Your clone might not be complete.

**Comment by tomjoht** [comment]
Try deleting the Gemfile and Gemfile.lock files entirely.  After deleting those files, run `gem install jekyll` and then `jekyll serve`.

**Comment by arturbosch** [comment]
I tried this again and unfortunately it does not work.
The github api authentication should not lead to css and js not found, should it?

**Comment by kastork** [comment]
When I did a fresh clone of the site just now and ran it (`docker-compose up`).  I got the following error:

```
Creating documentationthemejekyll_server_1 ... done
Attaching to documentationthemejekyll_server_1
server_1  | Configuration file: /src/_config.yml
server_1  |             Source: /src
server_1  |        Destination: /src/_site
server_1  |  Incremental build: disabled. Enable with --incremental
server_1  |       Generating...
server_1  |    GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
server_1  | jekyll 3.6.2 | Error:  Invalid US-ASCII character "\xE2" on line 5
server_1  |   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
server_1  |                     Invalid US-ASCII character "\xE2" on line 5
documentationthemejekyll_server_1 exited with code 1
```

So maybe that file is causing problems for you as well.  (`Invalid US-ASCII character "\xE2" on line 5`)

**Comment by prees1** [comment]
Are you viewing `http://127.0.0.1:4000` or `http://127.0.0.1:4000/documentation-theme-jekyll/` in your browser?

I see what you are seeing if I view `http://127.0.0.1:4000`.

Going to `http://127.0.0.1:4000/documentation-theme-jekyll/` worked for me.

**Comment by arturbosch** [comment]
Uff thanks @prees1. That was the issue ... :)
