### ISSUE TITLE
Sidebar does not scroll

### ISSUE THREAD

**Issue by mbatchkarov** [tomjohnson1492/documentation-theme-jekyll#12]
When a sidebar entry contains links to lots of pages, the list is truncated at the bottom of the screen, whereas it should scroll.

To replicate:
- open [a page](http://idratherbewriting.com/documentation-theme-jekyll/mydoc/mydoc_about.html). I'm running Firefox 43 on OSX, but the same happens in Chrome and Safari.
- shrink your browser window's height. I'm using a window size of about 1400x700 px.  It needs to be wide enough to prevent the mobile layout from kicking in, but also not tall enough to display the entire list of pages in the sidebar.
- click to expand `Publishing` in the sidebar. You should see only some of the entries in that menu.
- Try scrolling 

It might be easier to reproduce if more entries are added to the sidebar. I've got about 50 articles in one category- that's where I'm seeing the problem.

**Comment by mbatchkarov** [comment]
OK, it's not a bug, it's a [feature](https://github.com/tomjohnson1492/documentation-theme-jekyll/blob/gh-pages/js/customscripts.js#L12). I'm not sure I understand why it is needed though. 

Even if making the sidebar float is necessary, it shouldn't be done just once on document load, because it won't respond to window resize event.

**Comment by tomjoht** [comment]
Thanks for the feedback. I'm not entirely sure how this CSS should be coded there. I'm sure there's a more graceful approach, but I'm not really a UI designer so I just did the best I could. Originally, I had the sidebar float continuously. But then I ran into problems when the sidebar was too tall for a smaller viewport. Hence the code that changes class when the viewport is smaller.

**Comment by tomjoht** [comment]
I'm going to close this since I don't have a fix for this now. If you would like to fork the theme and contribute a fix for this, I will gladly merge it in. Basically there would need to be a JS script that get triggered when a sidebar heading is expanded and looks to see if the height of the sidebar extends beyond the height of the page, and if so, removes the class on the sidebar that affixes the sidebar in place.

**Comment by tsdev** [comment]
I am having the same problem.

**Comment by tomjoht** [comment]
In customscripts.js, adjust the value here: 

```
   if (h > 800) {
        $( "#mysidebar" ).attr("class", "nav affix");
    }
```

change 800 to something larger, like 1200, if this is an issue. The theme does not provide sidebar scrolling when the sidebar extends beyond the height of the page.
