### ISSUE TITLE
Docker Compose deployment fails in scss style file

### ISSUE THREAD

**Issue by kastork** [tomjohnson1492/documentation-theme-jekyll#124]
Following the instructions in the Docker section of getting started.  The server fails to start with the following error:

```
Successfully built 16098df361ea
Successfully tagged result/latest:latest
Recreating ..._server_1 ... done
Attaching to ..._server_1
server_1  | Configuration file: /src/_config.yml
server_1  |             Source: /src
server_1  |        Destination: /src/_site
server_1  |  Incremental build: disabled. Enable with --incremental
server_1  |       Generating... 
server_1  |    GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
server_1  | jekyll 3.6.2 | Error:  Invalid US-ASCII character "\xE2" on line 5
server_1  |   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
server_1  |                     Invalid US-ASCII character "\xE2" on line 5

```

**Comment by Romain63** [comment]
Same issue here

**Comment by tomjoht** [comment]
I probably need to just remove the Docker section. I don't work with Docker. Someone else added this and I merged the PR.

**Comment by kastork** [comment]
Leave it in, I’ll see if I can update it

**Comment by holmrenser** [comment]
This also happens outside of Docker. See #130.

**Comment by weipah** [comment]
I can run the current state of the project fine in docker. There also is no such file "assets/css/style.scss".

"_site/assets/css/style.css" on the other hand builds fine during _jekyll serve_.
Have you tried to empty your __site_ folder?

**Comment by kastork** [comment]
Docker situation was mostly fixed.  https://github.com/tomjoht/documentation-theme-jekyll/pull/126
