### ISSUE TITLE
xml sitemap

### ISSUE THREAD

**Issue by moabi** [tomjohnson1492/documentation-theme-jekyll#13]
in order to be valid, the sitemap needs the full url, 
Add a variable with hostname as a prefix
hostname: https://mydoc.com

**Comment by moabi** [comment]
`<last_updated>`
 is an unknown tag and therefore can't pass Google xml Validation

Use :     

`<lastmod>`

**Comment by tomjoht** [comment]
One problem is that I'm using relative paths throughout for this theme, with the idea that you'll be publishing multiple outputs. If I add an absolute link here in the sitemap, the sitemap will be more tied to a specific URL. Maybe this is just a requirement for web optimization.

**Comment by tomjoht** [comment]
A url has been added to the _config file. This should fix the issue with the url missing from the sitemap.
