### ISSUE TITLE
edit gitlab link in _layouts/page.html

### ISSUE THREAD

**Issue by florianap** [tomjohnson1492/documentation-theme-jekyll#134]
In lines 49-53 of _layouts/page.html the URL should be Gitlab and instead it's Github:

please change line 51 into:
 
    <a target="_blank" href="https://gitlab.com/{{site.gitlab_editme_path}}{% unless page.url contains "index.html" %}pages/{% endunless %}{{page.folder}}{{page.url | remove: ".html" | append: ".md"}}" class="btn btn-default githubEditButton" role="button"><i class="fa fa-gitlab fa-lg"></i> Edit me</a>

**Comment by tomjoht** [comment]
I'm not sure why you want to change Github to Gitlab. They are different sites entirely.
