### ISSUE TITLE
Add `jekyll-theme` topic to repo

### ISSUE THREAD

**Issue by nickswalker** [tomjohnson1492/documentation-theme-jekyll#135]
GitHub uses the `jekyll-theme` [topic listing](https://github.com/topics/jekyll-theme) in their [blog post](https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/) highlighting gem-based theme support for GitHub pages. Adding the topic to this repo would help others discover the theme.

**Comment by tomjoht** [comment]
I think 90% of people who use the theme customize it heavily with their own branding. I have a major revamp I'd like to push out before offering gem-based theme support, but I'll prob do this in the future. Thanks for the note.
