### ISSUE TITLE
Versioning support?

### ISSUE THREAD

**Issue by vin-ni** [tomjohnson1492/documentation-theme-jekyll#136]
Does this theme also support Versioning via multiple branches?

**Comment by jmfrenzel** [comment]
The https://github.com/samvera/samvera.github.io  fork might have such feature, e.g. http://samvera.github.io/configuration-2.1.html

**Comment by vin-ni** [comment]
Thanks, I'll take a look at it. For now I went with [readthedocs](https://readthedocs.org/).
