### ISSUE TITLE
how may i remove the excerpt column in the table of pages for a tag

### ISSUE THREAD

**Issue by HungryOrc** [tomjohnson1492/documentation-theme-jekyll#138]
Thanks!

**Comment by ghost** [comment]
You'd need to edit your local copy of _includes/taglogic.html to build a table to your specification. (I found that by searching the project for "excerpt" to find where the table is being built.)

I think this is the kind of customization that probably doesn't belong in the main theme, but that you'd do to get the specific thing you want.

**Comment by HungryOrc** [comment]
Thank you so much Robert! It is very helpful!

**Comment by tomjoht** [comment]
It looks like you were able to remove the excerpt feature. I'll add some info into the docs in the future about this.

**Comment by tomjoht** [comment]
BTW, I added it in there as a forcing function for a documentation best practice. Summaries are almost always helpful (but sometimes challenging to write).
