### ISSUE TITLE
how may i remove the comments at the bottom of each page

### ISSUE THREAD

**Issue by HungryOrc** [tomjohnson1492/documentation-theme-jekyll#139]
Thanks!

**Comment by ghost** [comment]
You can do this on your local copy of the theme by removing `{% include disqus.html %}` from your layouts. The page and post layouts have that by default in the theme.

(I found this by searching the theme source files for "disqus" after I noticed that the comment system is based on Disqus.com.)

**Comment by HungryOrc** [comment]
Thank you so much Robert!!

**Comment by tomjoht** [comment]
Thanks for helping out here with the comments.
