### ISSUE TITLE
Company logo not shown anywhere

### ISSUE THREAD

**Issue by mrchief** [tomjohnson1492/documentation-theme-jekyll#14]
It should appear in the footer at least based on what I've gleaned so far but it doesn't. Is it a bug or am I missing something?

Even the demo site is missing it.

**Comment by tomjoht** [comment]
Thanks for pointing out the issue. I fixed it just now. In the footer.html file in the includes folder, I was missing a closing quote mark in the footer image variable. Also, in the configuration file, I needed another ../ in the path.

**Comment by mrchief** [comment]
:+1: Even after scanning that line several times, I couldn't see the missing quote. Or maybe I did and it didn't work since I was missing the other `../` in config. Anyway, glad you fixed it. Awesome work on this repo though!
