### ISSUE TITLE
Tocpage.html and prince-list.txt are empty

### ISSUE THREAD

**Issue by matsamentet** [tomjohnson1492/documentation-theme-jekyll#143]
I'm following the guide to publish my site to PDF. Running the command
`bundle exec jekyll serve --detach --config _config.yml,pdfconfigs/config_mydoc_pdf.yml`
builds the site in PDF mode, but the resulting prince-list.txt and tocpage.html are both empty. It almost seems as if the sidebar YML which is referred in the config YML is not read properly. The sidebar YML works as it should when serving the site, though. Anyone know what could be wrong here?

**Comment by steeladept** [comment]
The default.html layout in _layouts and head.html in the _includes folder is what defines what is printed on the web.  The default_print.html layout and head_print.html header file are included when printing to PDF.  TOC is not included, by default, on the head_print.html file like it is on the head.html file.  Did you add it in there after the fact?  I can only assume prince-list.txt suffers from a similar issue, but without more information that is not possible to determine.

**Comment by matsamentet** [comment]
I should have answered my own question here but I forgot. It turned out I had an older version of the theme where there was a bug in the script which generates prince-list.txt. The newest version solved the problem.
