### ISSUE TITLE
Is it possible to do this?

### ISSUE THREAD

**Issue by steeladept** [tomjohnson1492/documentation-theme-jekyll#144]
I am learning Jekyll, and found your theme one of the most instructive and well designed themes to learn how to publish via Jekyll.  Further, it is so well documented, that it is relatively easy to go through and edit/change as desired without breaking everything from the ground up.  Kudos to you for that!

What I am trying to figure out how to do, however, is somewhat complicated and may not be possible.  Or maybe it is and I just have to keep working at it.  Basically, what I want is the NEWS section to comb through each of the products and post a new entry for any posts newer than the last x number of days (30 days for example).  I can simulate the idea by putting the post in both locations - _posts AND the product folder, but I would rather create a layout that reads through each product folder and "places" them in the _posts folder automatically at build time.  I will try to figure it out, but thought I should ask is there a way of making that happen?

**Comment by testaccount4blog** [comment]
I saw no response, so I learned how to make it happen myself.  It actually is quite easy, just add the override settings to the theme.  They load after the default bootstrap css, so they take precedence.  I am creating 2 pull requests for a blue-dark and green-dark theme options to consider.

**Comment by steeladept** [comment]
Let's try this again with the RIGHT account :)

I didn't see a response, so I looked closely at the theme, figured out how it was put together (css wise), and found how to make a dark theme.  It is suprisingly simple.  Because the bootstrap css loads before the theme css, any entries in the theme css override those in bootstrap.  So without changing anything else, if you just add the following lines to the top of your theme-<color>.css and rename (I recommend theme-<color>-dark.css); and then address it in the head.html in the _includes folder, you can have a dark theme based off the same colored light theme:

```
/* These colors are used to override bootstrap.min.css */

body {
    background-color: #333333;
    color: #d0d0d0;
}

table {
    color: #808080;
}

/* The rest of these settings are from the original light theme */
```

Alternatively, I can issue a pull request if provided the rights to do so.

**Comment by tomjoht** [comment]
I'm a little confused by your two messages. The first message talks about automatically listing blog posts for items found in products, while the second addresses theming. Maybe they're two different issues? At any rate, it looks like you solved the issue on your own. Sorry for the late reply.
