### ISSUE TITLE
how to add new blogs and make it link to sidebars

### ISSUE THREAD

**Issue by jeannotes** [tomjohnson1492/documentation-theme-jekyll#145]
hi, I write a blog, how to link to side bars

**Comment by steeladept** [comment]
You need to add the links in the _data>sidebars folder for whichever sidebar.yml file you are using on that page.

I recommend you put it on the home_sidebar.yml (probably the one you are looking for); however, with a blog, that can get annoying when the news feed layout option already provides the functionality you need most (there is currently no similar functionality in the sidebar to autoread/autoload let alone in chronological order).  For me, I just leave it to /news.html which brings you to the blog homepage where you can see what is currently published in reverse chronological order. 

That said, it might be an interesting addition to the sidebar, especially if it can just display the last 3 months, for example.

**Comment by chanakavp** [comment]
Thanks for the answer. I was looking for the method to link pages I create to the sidebar, and this helped.

It would be nice this information can be added to: 
https://idratherbewriting.com/documentation-theme-jekyll/mydoc_pages.html

**Comment by tomjoht** [comment]
Thanks for helping out with questions and answers here. Re the blog in general, since the theme is for documentation, I'm not really sure the blog is all that helpful. I might remove it in an upcoming version to simplify things.
