### ISSUE TITLE
Missing home.html

### ISSUE THREAD

**Issue by mrchief** [tomjohnson1492/documentation-theme-jekyll#15]
Running the site locally without any modifications (just downloaded the release zip and `jekyll serve`) launches the site but you're greeted with a page not found message on the landing page. 

The demo site itself points to `mydoc/home.html` and if I navigate to `localhost:4009/mydoc/home.html`, I see the home page. 

Navigating to just `localhost:4009` produces that landing page which looks for `home.html` in the root directory (and is missing).

**Comment by tomjoht** [comment]
Hmmm, what browser are you using? Try serving up the page in a local web environment, using a tool such as XAMPP. The index.html homepage should redirect to a home.html page in a project subfolder. I just tried it in Chrome and it worked for me, so I'm not sure why it's not working for you.

**Comment by mrchief** [comment]
I tried in Chrome Canary and beta. I'm on Windows and I tried in 2 boxes, both with same result. I'm not familiar with XAMPP.

**Comment by tomjoht** [comment]
I haven't tried building the project on Windows. You'll probably run into
various issues on Windows. Try uploading the site to a folder on a web host
and see if you run into the same problem.

XAMPP gives you a local web environment so you don't have to upload content
to a web host to test it.

**Comment by mrchief** [comment]
Its not different on Windows. I can run and host stuff. And is the redirection happening via the host? I mean the host shouldn't matter since this is all supposed to be static content.

**Comment by tomjoht** [comment]
The latest version of the theme doesn't have redirects from the index page like the previous version did, so this issue is fixed.
