### ISSUE TITLE
Removing `mydoc`

### ISSUE THREAD

**Issue by brianfeister** [tomjohnson1492/documentation-theme-jekyll#16]
So we have this `mydoc` in the path for everything on the site, but it's in so many places: the directory structure, file names, and configuration files.  

Am I missing a quick and easy way to properly change this to reflect the correct subdirectory for my project?

**Comment by tomjoht** [comment]
The "mydoc" path represents one of many possible projects you might be publishing from the site. I have another iteration of this theme that has a different paradigm for publishing. If you can wait a week or so, I'll push it out there. Or I can send you the code now.

**Comment by tomjoht** [comment]
This is the [repo](https://github.com/tomjohnson1492/singlesite-documentation-theme-jekyll) where I'm keeping my rework of this theme. I haven't updated the documentation, but the code for the site is updated. It works more like a traditional jekyll site. Just download and run jekyll serve. What's majorly different is that you can have lots of different products each with their own sidebar, all publishing to the same site.  Again, the doc for this theme is outdated/inaccurate. I need to update it.

**Comment by brianfeister** [comment]
Thanks for the quick reply @tomjohnson1492, very grateful for your work on this project!

For me, the overall structure and layout that I'm looking for is more similar to this project than the other one you're working on for single, which you referenced in your comment above.  

So, I'm curious if you could point out some of the relevant files in your new project which highlight the changes you made in order to remove `mydoc` as the root project in this theme and then I can recreate those in my own project?

**Comment by tomjoht** [comment]
Essentially the original theme was designed with the idea that you're
single sourcing (meaning, pushing multiple outputs from the same source).
As a result, all the files for one product are in mydocs, and you create
other folders for other products. Everything is walled off like that.

What kind of documentation are you trying to create and publish?

**Comment by brianfeister** [comment]
API documentation for a development platform.  Not quite like swagger, more like "how to", code examples, knowledge base stuff.

**Comment by tomjoht** [comment]
What is it about the other theme that doesn't work for those needs? Sounds
like one output, one product.

**Comment by brianfeister** [comment]
It mostly works. My initial question was just about how to rename the base directory without a ton of find and replace.

**Comment by brianfeister** [comment]
Answer appears to be "negatory - lots of find & replace required".  I honestly don't know jekyll well enough to know if this is a jekyll problem or a problem with the theme.  Appreciate your starting point though, made massive changes and got what I wanted.

**Comment by chanakavp** [comment]
How do I make **product1** or **product2** the default product and remove **mydoc**?
