### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joek** [tomjohnson1492/documentation-theme-jekyll#17]
Hi,
I really like to thank you to share such a great theme. It looks like the best fit for our next documentation project and we are taking into account to use it. One thing I have not found so far is the License you are sharing this project. Could you please add a license file?

Cheers
Johannes

**Comment by tomjoht** [comment]
The license file is MIT. It's inside the licenses folder: https://github.com/tomjohnson1492/documentation-theme-jekyll/tree/gh-pages/licenses

**Comment by joek** [comment]
Ok, I was not searching for an folder. Thanks a lot
