### ISSUE TITLE
support jekyll-asciidoc

### ISSUE THREAD

**Issue by kastork** [tomjohnson1492/documentation-theme-jekyll#20]
This is a really cool theme, thank you.

Since this theme is documentation-centric, I think it would be great if you could use asciidoc in addition to markdown.

I've tried just adding the jekyll-asciidoc plugin, but I can't seem to get adoc files to process.  Either I get an error like `Error:  undefined method`empty?' for false:FalseClass` without any indication of what the offending file is (for just a regular page), or I get a post that has the raw asciidoc wrapped in a div.

Also, I'm just using the head of the repo, can't seem to find any "released" artifacts for this.

**Comment by javiboo** [comment]
+1

**Comment by tomjoht** [comment]
Thanks for the feedback and suggestion to support Asciidoc. Without doing more research, I'm not really sure what is involved in making this update. This update is beyond the scope of my current plans. Do you want to elaborate any more on the recommended approach?
