### ISSUE TITLE
How to Stop Sidebar from Collapsing

### ISSUE THREAD

**Issue by FA5I** [tomjohnson1492/documentation-theme-jekyll#202]
Hi,

This is a cool theme and I am excited to use it for my project.

One question I did have was is there a way to stop the sidebar from collapsing by default?

I set accordion = false in my sidebar.yml file but it did nothing. Any guidance is much appreciated.

**Comment by DelfCo** [comment]
My quick read of mydoc_sidebar_navigation.md is that there are two ways to get what you want. One involves editing the _includes/sidebar.html file, and the other involves changes to get yourself a fixed position sidebar. I don't get the impression that either one is a simple as setting accordion = false in a .yml file.

**Comment by FA5I** [comment]
Thanks @DelfCo! I will take a look at that

**Comment by FA5I** [comment]
I resolved by just disabling Navgoco, works good enough for my purposes.
