### ISSUE TITLE
does this still work with github-pages?

### ISSUE THREAD

**Issue by anirudha** [tomjohnson1492/documentation-theme-jekyll#22]
thanks

**Comment by tomjoht** [comment]
yes. in fact, I use Github pages to publish the theme.

**Comment by anirudha** [comment]
thanks for the quick reply, i had it working on github a few month ago it stopped working now. 

the demo link on github also is broken now.
http://idratherbewriting.com/documentation-theme-jekyll/mydoc/home.html
( this just needs to be updated to remove the mydoc/home.html)

i see build error on github:

and this error on my build mac
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in`map!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in`specs'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in`requested_specs'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in`setup'
    from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
    from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/plugin_manager.rb:33:in`require_from_bundler'
    from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.6/bin/jekyll:9:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in`load'
    from /usr/local/bin/jekyll:23:in `<main>'

**Comment by tomjoht** [comment]
Can you tell me where you found this link: http://idratherbewriting.com/documentation-theme-jekyll/mydoc/home.html

I searched across the project and couldn't find it.

Re the errors, try removing the Gemfile and gemlock files from your project. That's probably creating the issues. Alternatively, see http://idratherbewriting.com/documentation-theme-jekyll/mydoc_install_jekyll_on_mac/. Walk through the steps there. And also maybe read this for more background: http://idratherbewriting.com/documentation-theme-jekyll/mydoc_about_ruby_gems_etc/.
