### ISSUE TITLE
how can i add one more permalink

### ISSUE THREAD

**Issue by ghost** [tomjohnson1492/documentation-theme-jekyll#23]
i have added two permalink like below:
http://qinkun1234.github.io/b/mydoc_laravel5_1_manual/
but when i add the third permalink:
https://github.com/qinkun1234/b/commit/724500643d47e71275d8a06c85acc792542bc694

http://qinkun1234.github.io/b/mydoc_jwt/
it catch 404 File not found.
can u help me find where is the problem?

**Comment by tomjoht** [comment]
I'm not sure what you're really asking. Can you try downloading the latest version of the theme and let me know if this problem still persists?
