### ISSUE TITLE
The demo site has a javascript error

### ISSUE THREAD

**Issue by xx7y7xx** [tomjohnson1492/documentation-theme-jekyll#31]
Using Chrome(ver 51, windows) to browse the demo page: http://idratherbewriting.com/documentation-theme-jekyll/index.html

I got this error in Chrome console:

```
index.html:1076
Uncaught TypeError: $(...).annotator is not a function
```

**Comment by tomjoht** [comment]
Thanks. I fixed this. (I was experimenting with Annotator at one point and forgot to remove this reference.)
