### ISSUE TITLE
Auto-generating sidebar content from page headings

### ISSUE THREAD

**Issue by pch-envision** [tomjohnson1492/documentation-theme-jekyll#36]
Is there a feature to auto-generate sidebars from page headings?

For example:

```
- page 1
    - page 1 heading 1
    - page 1 heading 2
    - page 1 heading 3
- page 2
    - page 2 heading 1
    - page 2 heading 2
    - page 2 heading 3
```

I looked through the docs but nothing jumped out at me.

**Comment by tomjoht** [comment]
no, the sidebar isn't auto-generated. however, if you're interested in an
auto-generated sidebar based on frontmatter, ask Mike Neumegen from Cloud
Cannon. I know he's working on a theme that might align more with what
you're looking for.

**Comment by pch-envision** [comment]
Thanks for the quick answer and for your work on this theme!
