### ISSUE TITLE
Horizontal rules in markdown look wired in generated pages

### ISSUE THREAD

**Issue by Zhouxing-Su** [tomjohnson1492/documentation-theme-jekyll#37]
the horizontal rules in markdown seem to be a series of hyphen like the sreen shot below, instead of the "normal" appearance.

![image](https://cloud.githubusercontent.com/assets/5787025/17661824/2072b94a-6314-11e6-8864-67605bed1b15.png)

**Comment by tomjoht** [comment]
Thanks for the note. I made this fix.
