### ISSUE TITLE
Liquid Warning : Unexpected Character

### ISSUE THREAD

**Issue by bandit412** [tomjohnson1492/documentation-theme-jekyll#38]
I am getting the following warnings when running my site locally:

Liquid Warning: Liquid syntax error (line 9): Unexpected character { in "{{ "tag_" | append: {{tag}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 9): Unexpected character { in "{{ "tag_" | append: {{tag}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 10): Unexpected character { in "{{ "tag_" | append: {{tag}}" in pages/news/news.html

Everything "appears" to be working fine?

**Comment by tomjoht** [comment]
I think a later version of Liquid doesn't like this formatting. I'll need to update this to remove the syntax.

**Comment by ntncodex** [comment]
Liquid Warning: Liquid syntax error (line 8): Expected id but found pipe in "{{ page.date | | date: "%I %M %p ,%a, %b %d %Y"}}" in C:/jekyll/Goodtheme/_posts/2016-05-02-New-Presentation.markdown
    Liquid Warning: Liquid syntax error (line 2): Expected end_of_string but found pipe in "post in site.posts reversed | sort: title" in proselinks.jsonp

what on hell is all this i am getting confused now

**Comment by tomjoht** [comment]
wow, I've never seen that one before. Sorry, I have no idea. I'm guessing
that you have some content in
Goodtheme/_posts/2016-05-02-New-Presentation.markdown
that Liquid doesn't like. Try removing the content on the page and
re-adding it paragraph by paragraph to identify the problem.

**Comment by tomjoht** [comment]
I fixed the tag issue.
