### ISSUE TITLE
Mini TOC Script

### ISSUE THREAD

**Issue by tonysneed** [tomjohnson1492/documentation-theme-jekyll#4]
This is related to https://github.com/jekyll/jekyll-help/issues/298.  I have inserted an include for the toc.html file in my default layout html file, but the toc isn't showing up.  Looks like this may be a bit more complicated, with inclusion of some javascript for generating the toc?

This is what default.html looks like:

``` html
{% include head.html %}

    {% include nav.html %}

    <h1>{{ page.title }}</h1>

    <hr/>

    {% include toc.html %}

    <section id="main_content">

    <main role="main">
        {{ content }}
    </main>

{% include foot.html %}
```

In my head.html I'm including: `<script src="{{ "/js/toc.js" | prepend:site.baseurl }}"></script>`, and I placed toc.js in a js folder.  I'm guessing that I'm missing something.

**Comment by tomjoht** [comment]
I assume you're talking about the mini-TOC that includes page metadata. Make sure that in your configuration file, you have the following:

```
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
```

The `with_toc_data` argument means that when Jekyll processes your Markdown, it will include ID attributes in headers. If you just use HTML, you must manually include the ID attributes.

Other things to check: 
- Make sure you reference toc.js in your theme.

```
   <script src="{{ "/js/toc.js" | prepend:site.baseurl }}"></script>
```
- Make sure you include this where you want to put the toc:

```
<div id="toc"></div>
```
- Make sure something in your JS isn't broken. Try inspecting the console and seeing if something else is blocking JS.

**Comment by tonysneed** [comment]
Great info, thanks.  I don't see anything in the console to indicate that Javascript is being blocked.

I also found this, which is in line exactly with what you're saying:
https://github.com/ghiculescu/jekyll-table-of-contents

Working on it .. I'll update you on my success.

**Comment by tonysneed** [comment]
So far no luck in getting the toc to show up.  I think I've done everything I'm supposed to do.  If it's not asking to much, would you mind having a look at my repo?

https://github.com/tonysneed/trackable-entities/tree/gh-pages-toc

You'll find there the following files, which I've modified to incorporate the mini TOC:
- _config.yml
- javascripts/toc.js
- toc.html
- head.html
- default.html

From what I understand, what should be happening is that toc.js should be called on page ready, so that the toc will be inserted where `<div id="toc"></div>` is located, and the `##` headers are contained in the markdown.  Thanks in advance! :smile:

**Comment by tomjoht** [comment]
Hi Anthony. I took a look at your theme. It seems that jQuery is a
dependency for the script to work. In your head.html file, paste this in:

<script src="
https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

Then the toc.js will work.

I asked the toc.js developer to note the jQuery dependency in the docs.

---

blog: idratherbewriting.com
twitter: tomjohnson
408-540-8562
