### ISSUE TITLE
Support Jekyll Gem-based Theme

### ISSUE THREAD

**Issue by allejo** [tomjohnson1492/documentation-theme-jekyll#45]
Is it possible to support this theme as a [Gem-based Jekyll theme](https://jekyllrb.com/docs/themes/)?

**Comment by tomjoht** [comment]
Potentially. This is on my to-do list but I haven't gotten around to it. The next iteration will likely make changes to allow for translation, which is a larger issue in scaling Jekyll.

**Comment by tomjoht** [comment]
I'm going to close this issue and keep the gem-based theme support on the future roadmap. I really think people benefit from seeing all the theme files, so I'm not entirely persuaded to the gem-based model anyway.

**Comment by afred** [comment]
@tomjohnson1492 Hey, we're interested in making this a gem for ease of maintenance. We have some capacity and could help you out to that end.

**Comment by tomjoht** [comment]
i'm open to this. let me go through the list of recent PRs first and see what i want to merge.

**Comment by elrayle** [comment]
I work in the same community as @afred.  I created a gem version of this template.  You can review it at...  https://github.com/elrayle/documentation-theme-jekyll

**Comment by tomjoht** [comment]
Hey, it's great to see the gem-based theme version here. Nice work. I do have plans to roll in something similar, but I'd been reworking a new version of this theme that was localization friendly and never really finished pushing it out.

**Comment by elrayle** [comment]
NOTE: We are running into a challenge with the gem when trying to override things like the company logo, css, etc.  Jekyll documentation states you can override assets by putting an assets directory in the app including the gem and using the same name file.  

Overrides work when the files are directly under assets...
```
/assets/customstyles.css
/assets/companylogo.png
...
```
Overrides don't work if these files are nicely organized in subfolders...
```
/assets/css/customstyles.css
/assets/images/companylogo.png
...
```

This seems like it might be a jekyll problem.

Related Jekyll doc:  https://jekyllrb.com/docs/themes/#overriding-theme-defaults

**Comment by tomjoht** [comment]
Interesting. I didn't know that. I'm going to be converting another doc theme to a gem-based theme shortly, so I'll keep an eye out for this issue. I appreciate the note. It seems like the temporary fix is to not use subfolders?
