### ISSUE TITLE
HTML table generation issues with `markdown="1"` attribute

### ISSUE THREAD

**Issue by larrykollar** [tomjohnson1492/documentation-theme-jekyll#48]
In http://idratherbewriting.com/documentation-theme-jekyll/mydoc_tables.html

![screen shot 2016-11-03 at 9 35 45 pm](https://cloud.githubusercontent.com/assets/16429595/19991658/ab5474da-a20d-11e6-86ec-70457871ff2e.png)

Looking at the generated HTML markup, the ending `</td>` tag is getting picked up as Markdown and rendered as `&lt;/td&gt;`. That's breaking all tables all the way down the line. This might be a Jekyll issue rather than with the theme.

The quick and dirty workaround: move the ending `</td>` tag to a new line.

Another, more minor issue: cells with the `markdown="1"` attribute are rendered vertically centered, while other cells in the same row are rendered top-justified. That's probably a CSS issue. Keeping all cells consistent is the workaround there.

**Comment by tomjoht** [comment]
Thanks for the note. I made the fix.
