### ISSUE TITLE
The Topnav dropdown doesn't show the subitems

### ISSUE THREAD

**Issue by patrickdaulie** [tomjohnson1492/documentation-theme-jekyll#5]
When clicking the dropdown menu in the topnav section, the subitems defined in the topnav.yml do not appear.

![screen shot 2015-06-07 at 21 33 00](https://cloud.githubusercontent.com/assets/10108618/8025631/d98a45d8-0d5c-11e5-82bc-01bb2bb40541.png)

**Comment by tomjoht** [comment]
Check to make sure that the config file has all the right conditions, and that the top nav and its submenu items also have the right conditions. if all the conditions are there and it's still not showing, it could be a bug in the theme. i need to push out a newer version.

**Comment by patrickdaulie** [comment]
Thanks. I'll take a look. 
It also appears to be the case on the example : http://idratherbewriting.com/documentation-theme-jekyll/

**Comment by tomjoht** [comment]
You're right. I need to fix that. Just curious, but do you really plan to
use all of those conditions? If you aren't single sourcing, you can
drastically simplify the menu and code.

In the includes, in topnav.html and sidebar.html, you would just remove
stuff like this:

{% if subcategory.audience contains audience and subcategory.product
contains product and subcategory.platform contains platform and
subcategory.version contains version and subcategory.web != false %}

as well as the closing {% endif %}

I did that with my blog (http://idratherbewriting.com), which is using the
same base theme but modified to strip out the conditions.

For work, though, I have around 16 different outputs to produce from the
same jekyll project, so I needed all of those conditions.

---

blog: idratherbewriting.com
twitter: tomjohnson
408-540-8562

**Comment by tomjoht** [comment]
This issue has been fixed.
