### ISSUE TITLE
Docker build directions fail

### ISSUE THREAD

**Issue by anthonysimone** [tomjohnson1492/documentation-theme-jekyll#54]
I had problems spinning the project up with the docker build instructions. It seems like one of the ruby packages requires a more recent version of ruby, I got the error `activesupport-5.0.0.1 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 2.1.10p492`.

I changed `FROM ruby:2.3` to `FROM ruby:2.3` and re-ran the two commands and it worked. I'm hesitant to suggest this as a PR because I don't really work with ruby/docker, so I'm not sure if it really makes sense to use that version of ruby.

**Comment by tomjoht** [comment]
Thanks for reporting the issue. Someone else actually contributed the Docker build instructions, so let me follow up with that person about the fix. I myself am not that familiar with Docker.

**Comment by hartzell** [comment]
FWIW, the Dockerfile works for me with Docker 1.13.0 on a mac (Docker Mac, or whatever their branding team has decided to call it this week...).

**Comment by tomjoht** [comment]
If it works for you, then I'll close this issue. As I said, I personally don't use Docker, so this is a little outside of my zone of direct experience.
