### ISSUE TITLE
Invalid CSS in customstyles.css

### ISSUE THREAD

**Issue by ghost** [tomjohnson1492/documentation-theme-jekyll#57]
https://github.com/tomjohnson1492/documentation-theme-jekyll/blob/82e4157a86b9d6e41a672b3f26a6619dbb2b4034/css/customstyles.css#L164-L166 is invalid CSS code.
The code was introduced by f8b960225e14af08cb140ce3a259d5f8ff534980 and as I do not know what its intention was, I purposely did not simply create a pull request removing it.

**Comment by tomjoht** [comment]
thanks for the note. i removed this erroneous style.
