### ISSUE TITLE
Unable to filter based on audience

### ISSUE THREAD

**Issue by apclee** [tomjohnson1492/documentation-theme-jekyll#6]
Generating the docs based on audiences.  This seems to work for the sidebar and topnav.  However, all pages regardless of the audience associated with them are still printed.

**Comment by tomjoht** [comment]
yeah, you have to exclude the pages that you don't want. sorry I didn't
make that clear in the documentation. put something like this in your
configuration file:

exclude:
- _drafts
- bower_components
- getting_started
- full_setup
- acme_setup
- logs
- user_management
- administrator
- pages/acme
- pages/gizmo

it gets tricky depending upon how many outputs you have.

---

blog: idratherbewriting.com
twitter: tomjohnson
408-540-8562
