### ISSUE TITLE
Java runtime 

### ISSUE THREAD

**Issue by ashutoshmjain** [tomjohnson1492/documentation-theme-jekyll#67]
Hi Tom @tomjohnson1492 

First of all, thanks for this wonderful theme. 

I have some issue in starting the Jekyll server at my local machine. Here is the error that I am getting. Let me know if you have seen this message before. I am on Slackware 14.2 and followed the getting started instructions to upgrade the bundle..

`bash-4.3$ bundle exec jekyll serve
Configuration file: /home/ashutosh/documentation/_config.yml
Configuration file: /home/ashutosh/documentation/_config.yml
jekyll 3.3.1 | Error:  Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
`
After seeing this message, I installed the execjs too from above link. But it didn't work. 

Thanks in advance

**Comment by tomjoht** [comment]
I've never seen that error. I'm not sure what Slackware 14.2 even is. Can you install and run a vanilla jekyll site? did you try bundle install?

**Comment by ashutoshmjain** [comment]
Tom - Thanks for the response. 
Slackware is a Linux distribution. 14.2 being their latest release. 
Yes , I have Jekyll server running for other Jekyll based websites. I suspect its the jekyll version 3.3.1 causing the issue ..
Yes, I did Bundle install. I upgraded bundler to to latest version 1.14. Then I did bundle update . It did work..

**Comment by tomjoht** [comment]
Great. Thanks for the follow-up.
