### ISSUE TITLE
Separate products from main template

### ISSUE THREAD

**Issue by debovema** [tomjohnson1492/documentation-theme-jekyll#70]
Hello,

First of all, thanks for this great theme.

Is there a plan to separate the products from the other files of the theme?

The idea would be to have the content of a product's documentation in a separate Git repository so it could have its own lifecycle.
The actual build could be performed either by providing a way to import the main project (containing the theme's files) in a product's project or simply by defining the product's repository as a submodule of the main one.

To do so, not only the pages of a product should be in a subfolder (such as "pages/product1" currently) but all the other references especially the sidebar of the product.

Thanks in advance.

**Comment by tomjoht** [comment]
I'm intrigued by this, but I'm not sure how to pull it off. Can you expand with more details on your recommended update?

**Comment by debovema** [comment]
Sorry for late answer

If you look in _pages/_ subfolder you have the 3 following subfolders :
* mydoc
* product1
* product2

which is good as it allows to separate the content of different products.

My idea would be to go further in this separation by moving the content of these three folders to separate Git repositories.
Then I would use the submodule feature of Git to reference the 3 external Git repsositories and your template could still generate the full documentation (HTML) and export each product to a single PDF (with Git submodule, it is possible to have all files in _pages/product*_ folders of the main repository even though the files are saved on separate Git repositories).

Unfortunately, this is not possible to do so because there are other references to the products in the template. For instance, in __data/sidebar_, there are _mydoc_sidebar.yml_, _product1_sidebar.yml_ and _product2_sidebar.yml_ files.

What I would like is a way to move all these references in a unique folder (such as _pages/product*_ folders).

**Comment by debovema** [comment]
Might be useful : https://jekyllrb.com/tutorials/navigation/#scenario-7-retrieving-items-based-on-front-matter-properties

**Comment by tomjoht** [comment]
sorry for the delay in responding here. in thinking this over, my strategy is to make the theme into a rubygem so that each repo can easily pull the theme files in, rather than using submodules for content. submodules introduces more complexity than i want and isn't the standard approach jekyll has taken for theming.
