### ISSUE TITLE
Load remote markup

### ISSUE THREAD

**Issue by onlykey** [tomjohnson1492/documentation-theme-jekyll#78]
Hey great project. I have been trying this out as a documentation site and it works well. One issue I have though is that I would like to load remote README.md files from other repos I have. This is possible with this and other plugins - https://github.com/Rolinh/jekyll-remote-markdown

So I create the _plugins directory, upload the remote_markdown.rb, and put a tag in one of my pages like this:

{% remote_markdown https://raw.githubusercontent.com/Rolinh/jekyll-remote-markdown/master/README.md %}

All that happens is it just keeps showing the old page and never renders a new page. Should this work? Is there another way to get this to work? Any help would be appreciated.

**Comment by tomjoht** [comment]
Sorry, I'm specifically not using plugins so that the theme can integrate with GitHub Pages. Pulling in content from other repos is important, for sure. But I want to find an approach that doesn't involve plugins.
