### ISSUE TITLE
five (not four) knowledge base cells ?

### ISSUE THREAD

**Issue by ghost** [tomjohnson1492/documentation-theme-jekyll#92]
I'd like to adapt the knowledge-base layout to show five cells/icons/panels instead of four. But when I just add another \<div> element with class="col-md-3 col-sm-6", I end up with the first four nicely top-aligned, but the fifth one appears below the forth one.

Any advice?

If I narrow the window width, I get three rows, but the fifth item is in the 2nd column instead of the first. If I narrow the window some but not enough to push any of the items to a next row, the fa (font awesome) icons lose their centered-ness.

**Comment by tomjoht** [comment]
I believe that you just need a stronger understanding of the Bootstrap grid. See https://bootstrapdocs.com/v3.3.6/docs/css/#grid-options for more details. I can't dive into the guts of this for now, but basically the grid has a maximum number of columns (12), and I think you're exceeding it with your modification.
